### ISSUE TITLE
сам метод не принимает никаких аргументов кроме коллбэка

### ISSUE THREAD

**Issue by solarrust** [stanislawkostenko/bjs-diplom#2]
https://github.com/stanislawkostenko/bjs-diplom/blob/92ca858220bf414ae5294eea032100dba5b28946/static/main.js#L9

**Comment by stanislawkostenko** [comment]
Не нашёл что поправить, так как лишних аргументов не было, изначально стоял коллбэк, на что вы уже указывали несколько коммитов назад.
