### ISSUE TITLE
метод создания пользователя принимает только коллбэк в качестве аргумента

### ISSUE THREAD

**Issue by solarrust** [stanislawkostenko/bjs-diplom#5]
https://github.com/stanislawkostenko/bjs-diplom/blob/92ca858220bf414ae5294eea032100dba5b28946/static/main.js#L87

```
SGuslicky.addNewUser((err, data) => { ... }
```

**Comment by stanislawkostenko** [comment]
убрал лишние аргументы, оставив лишь коллбэк (err, data)
